DROP TABLE IF EXISTS active_directory;
CREATE TABLE active_directory (
    id bigint,
    event_id text,
    device_id text,
    g_timestamp timestamp with time zone,
    user_id text,
    prior_user_id text,
    g_ip inet,
    s_ip varchar(255),--inet,
    t_ip inet,
    transport_proto bigint,
    t_port bigint,
    s_port bigint,
    g_hostname text,
    s_hostname text,
    t_hostname text,
    malware_id text,
    s_bytes text,
    t_bytes text,
    http_status text,
    http_method text,
    http_hostname text,
    http_agent text,
    mime_type text,
    uri text,
    corr_count text,
    g_zone_id bigint,
    s_zone_id bigint,
    t_zone_id bigint,
    nsm_type text,
    message text,
    instdevice_id text,
    priority text,
    acquire_timestamp timestamp with time zone,
    user_id_implementer text,
    user_id_requester text,
    user_id_approver text,
    "group_id" text,
    group_member_id text,
    object_name text,
    object_type text,
    process_executable text,
    object_access text,
    object_action text,
    in_interface text,
    out_interface text,
    mac text,
    g_mac text,
    s_mac text,
    t_mac text,
    ip inet,
    acquire_ip inet,
    tun_s_ip inet,
    tun_t_ip inet,
    n_s_ip inet,
    n_t_ip inet,
    hostname text,
    acquire_hostname text,
    icmp_code text,
    icmp_type text,
    n_s_port bigint,
    n_t_port bigint,
    s_email text,
    t_email text,
    http_referrer text,
    transaction_time text,
    acquire_zone_id text,
    zone_id text,
    device_backref text
)
WITH (appendonly=true, orientation=column, compresstype=quicklz) 
DISTRIBUTED BY (ID)
PARTITION BY RANGE(g_timestamp)
	(
PARTITION "prt_201203" start ('2012-03-01'::timestamp) END ('2012-04-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201204" start ('2012-04-01'::timestamp) END ('2012-05-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201205" start ('2012-05-01'::timestamp) END ('2012-06-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201206" start ('2012-06-01'::timestamp) END ('2012-07-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201207" start ('2012-07-01'::timestamp) END ('2012-08-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201208" start ('2012-08-01'::timestamp) END ('2012-09-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201209" start ('2012-09-01'::timestamp) END ('2012-10-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201210" start ('2012-10-01'::timestamp) END ('2012-11-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201211" start ('2012-11-01'::timestamp) END ('2012-12-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201212" start ('2012-12-01'::timestamp) END ('2013-01-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201301" start ('2013-01-01'::timestamp) END ('2013-02-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201302" start ('2013-02-01'::timestamp) END ('2013-03-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201303" start ('2013-03-01'::timestamp) END ('2013-04-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201304" start ('2013-04-01'::timestamp) END ('2013-05-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201305" start ('2013-05-01'::timestamp) END ('2013-06-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
PARTITION "prt_201306" start ('2013-06-01'::timestamp) END ('2013-07-01'::timestamp) WITH (appendonly=true, orientation=column, compresstype=quicklz),
DEFAULT PARTITION OTHER WITH (appendonly=true, orientation=column, compresstype=quicklz)
);
